// Engineering Mathematics — Lecture Data
// Sections: Linear Algebra · Probability · Calculus (GATE 2025) · Calculus (Old Videos)
// Durations in minutes.

export const engmaths = {
  id: 'engmaths',
  name: 'Engineering Mathematics',
  shortName: 'Eng Math',
  icon: '📐',
  accent: 'emerald',
  defaultDailyGoalMins: 120,
  lectures: [

    // ─── Linear Algebra ──────────────────────────────────────────────────────

    { id: 1,  section: 'Linear Algebra', title: 'Lecture 1A - Why Study Linear Algebra',                                            duration: 22  },
    { id: 2,  section: 'Linear Algebra', title: 'Lecture 1B - Linear Algebra for GATE & Interviews',                                duration: 14  },
    { id: 3,  section: 'Linear Algebra', title: 'Lecture 1C - Linearly Independent and Linearly Dependent',                         duration: 75  },
    { id: 4,  section: 'Linear Algebra', title: 'Lecture 2A - Filling the Space Part 1',                                            duration: 44  },
    { id: 5,  section: 'Linear Algebra', title: 'Lecture 2B - Filling the Space Part 2',                                            duration: 28  },
    { id: 6,  section: 'Linear Algebra', title: 'Lecture 2C - Summary So far',                                                      duration: 12  },
    { id: 7,  section: 'Linear Algebra', title: 'Lecture 2D - Multiplying a Matrix & a Vector',                                     duration: 26  },
    { id: 8,  section: 'Linear Algebra', title: 'Lecture 3A - Homework 1 Discussion (Live)',                                        duration: 67  },
    { id: 9,  section: 'Linear Algebra', title: 'Lecture 3B - Why Solve System Of Linear Equations',                                duration: 22  },
    { id: 10, section: 'Linear Algebra', title: 'Lecture 3C - Writing as Ax=b, Geometric Interpretation and Possible Solutions',    duration: 24  },
    { id: 11, section: 'Linear Algebra', title: 'Lecture 3D - Understanding Ax=b intuitively',                                      duration: 44  },
    { id: 12, section: 'Linear Algebra', title: '4A. Multiplying 2 Matrices | My Walmart Interview Question',                       duration: 18  },
    { id: 13, section: 'Linear Algebra', title: '4B. GATE 2016 Question',                                                           duration: 16  },
    { id: 14, section: 'Linear Algebra', title: '4C. GATE 2014 Question',                                                           duration: 14  },
    { id: 15, section: 'Linear Algebra', title: '4D. Two conceptual questions',                                                     duration: 28  },
    { id: 16, section: 'Linear Algebra', title: '4E. Linear Combination of Independent vectors is unique',                          duration: 28  },
    { id: 17, section: 'Linear Algebra', title: '4F. GATE 2017 Question',                                                           duration: 4   },
    { id: 18, section: 'Linear Algebra', title: '5A. Echelon Form and Pivot Columns',                                               duration: 37  },
    { id: 19, section: 'Linear Algebra', title: '5B. Gaussian Elimination',                                                         duration: 26  },
    { id: 20, section: 'Linear Algebra', title: '5C. Rank | GATE 1994 Question | Rank Nullity Theorem',                             duration: 11  },
    { id: 21, section: 'Linear Algebra', title: '5D. Finally Solving Ax=b | Five Different Questions',                              duration: 33  },
    { id: 22, section: 'Linear Algebra', title: '5E. More than one free variable in 𝐴𝑥=0 solution',                                 duration: 32  },
    { id: 23, section: 'Linear Algebra', title: '6A. GATE 2021 Question | Free variables in Non homogeneous',                       duration: 19  },
    { id: 24, section: 'Linear Algebra', title: '6B. Solutions based on Rank(A) and Rank(A|b)',                                     duration: 18  },
    { id: 25, section: 'Linear Algebra', title: '6C. Few Questions related to rank(A) and Number of solutions',                     duration: 8   },
    { id: 26, section: 'Linear Algebra', title: '6D. [OPTIONAL] Linearly Independent Columns with Gaussian Elimination',            duration: 24  },
    { id: 27, section: 'Linear Algebra', title: '6E. [Optional] Row Reduced Echelon Form',                                          duration: 28  },
    { id: 28, section: 'Linear Algebra', title: 'Lecture 7A. Determinant',                                                          duration: 100 },
    { id: 29, section: 'Linear Algebra', title: 'Lecture 7B. Inverse of a Matrix (Live)',                                           duration: 87  },
    { id: 30, section: 'Linear Algebra', title: 'Lecture 7C. Crammer\'s rule',                                                      duration: 26  },
    { id: 31, section: 'Linear Algebra', title: 'Lecture 8A. Introduction to Eigenvalues and Eigenvectors',                         duration: 23  },
    { id: 32, section: 'Linear Algebra', title: 'Lecture 8B. Characteristic Equation',                                              duration: 15  },
    { id: 33, section: 'Linear Algebra', title: 'Lecture 8C. Solving for Eigenvalues and Eigenvectors',                             duration: 22  },
    { id: 34, section: 'Linear Algebra', title: 'Lecture 9A. Linearly Independent Eigen vectors with repeating eigenvalues',        duration: 21  },
    { id: 35, section: 'Linear Algebra', title: 'Lecture 9B. Three Different Examples With Repeating Lambda',                       duration: 30  },
    { id: 36, section: 'Linear Algebra', title: 'Lecture 9C. Symmetric Matrices has n LI Eigen Vectors',                           duration: 12  },
    { id: 37, section: 'Linear Algebra', title: 'Lecture 9D. Two Magical Properties',                                               duration: 12  },
    { id: 38, section: 'Linear Algebra', title: 'Lecture 10A. Rank and Eigen Values',                                               duration: 22  },
    { id: 39, section: 'Linear Algebra', title: 'Lecture 10B. Examples on Rank and Eigen Values',                                   duration: 15  },
    { id: 40, section: 'Linear Algebra', title: 'Lecture 10C. CAYLEY-HAMILTON THEOREM',                                             duration: 16  },
    { id: 41, section: 'Linear Algebra', title: 'Lecture 10D. Eigen Values of AB and BA',                                          duration: 32  },
    { id: 42, section: 'Linear Algebra', title: 'Lecture 10E. Eigen Values of Powers of A',                                        duration: 17  },
    { id: 43, section: 'Linear Algebra', title: 'Lecture 10F. Three Tough/Interesting GATE PYQs (Live)',                            duration: 63  },
    { id: 44, section: 'Linear Algebra', title: 'Lecture 10G. Matrix Diagonalization (Brief)',                                      duration: 15  },
    { id: 45, section: 'Linear Algebra', title: 'Lecture 11A. LU Decomposition',                                                    duration: 25  },
    { id: 46, section: 'Linear Algebra', title: 'Lecture 11B. Type Of Matrices',                                                    duration: 84  },
    { id: 47, section: 'Linear Algebra', title: 'LIVE Practice Questions on Linear Dependent Vectors',                              duration: 62  },
    { id: 48, section: 'Linear Algebra', title: 'LIVE Practice Questions on Solutions of Ax = b',                                   duration: 61  },
    { id: 49, section: 'Linear Algebra', title: 'LIVE Practice Questions on Linear Dependent Vectors and Solutions of Ax = b',      duration: 63  },
    { id: 50, section: 'Linear Algebra', title: 'LIVE Class on Practice Questions for GATE all Branches',                           duration: 53  },
    { id: 51, section: 'Linear Algebra', title: 'More GATE PYQs from all Branches',                                                 duration: 79  },
    { id: 52, section: 'Linear Algebra', title: 'Weekly Quizzes - Linear Algebra',                                                  duration: 0   },
    { id: 53, section: 'Linear Algebra', title: 'Review Annotated PDFs & Homework',                                                 duration: 0   },

    // ─── Probability ─────────────────────────────────────────────────────────

    { id: 54, section: 'Probability', title: 'Lecture 1A. Probability Definition, Sample Space and Events',                         duration: 28  },
    { id: 55, section: 'Probability', title: 'Lecture 1B. Inclusion Exclusion Principle, Demorgan\'s Law',                          duration: 37  },
    { id: 56, section: 'Probability', title: 'Lecture 2A. Conditional Probability Introduction',                                    duration: 34  },
    { id: 57, section: 'Probability', title: 'Lecture 2B. Conditional Probability Examples',                                        duration: 26  },
    { id: 58, section: 'Probability', title: 'Lecture 2C. Introduction to Tree Diagram',                                            duration: 32  },
    { id: 59, section: 'Probability', title: 'Lecture 3A. Total Probability',                                                       duration: 36  },
    { id: 60, section: 'Probability', title: 'Lecture 3B. Conditional Probability Examples',                                        duration: 33  },
    { id: 61, section: 'Probability', title: 'Lecture 3C: GATE PYQs Tree Method (Live)',                                            duration: 96  },
    { id: 62, section: 'Probability', title: 'Lecture 3D: GATE PYQs and Bayes Theorem (Live)',                                      duration: 107 },
    { id: 63, section: 'Probability', title: '[Optional] My LinkedIn Interview',                                                    duration: 49  },
    { id: 64, section: 'Probability', title: 'Lecture 4A. Independence of events',                                                  duration: 43  },
    { id: 65, section: 'Probability', title: 'Lecture 4B. Conditional Independence',                                                duration: 32  },
    { id: 66, section: 'Probability', title: 'Lecture 4C. Independence Does not imply Conditional Independence',                    duration: 22  },
    { id: 67, section: 'Probability', title: 'Lecture 4D. Random Variables Introduction (Live)',                                    duration: 113 },
    { id: 68, section: 'Probability', title: 'Lecture 5A. Practice Questions on Random Variables',                                  duration: 29  },
    { id: 69, section: 'Probability', title: 'Lecture 5B. More Practice Questions on Random Variables',                             duration: 67  },
    { id: 70, section: 'Probability', title: 'LIVE Session 5: Weekly Quiz 8 (Conditional Prob) Discussion',                         duration: 96  },
    { id: 71, section: 'Probability', title: 'Lecture 6A. Types of Random Variables',                                               duration: 9   },
    { id: 72, section: 'Probability', title: 'Lecture 6b. Probability Mass Function Questions Part 1',                              duration: 20  },
    { id: 73, section: 'Probability', title: 'Lecture 6c. Probability Mass Function Questions Part 2',                              duration: 15  },
    { id: 74, section: 'Probability', title: 'Lecture 7a. Expectation of Discrete Random Variable',                                 duration: 19  },
    { id: 75, section: 'Probability', title: 'Lecture 7b Expectation vs Average',                                                   duration: 40  },
    { id: 76, section: 'Probability', title: 'Lecture 7c. [Optional] Expectation as center of mass',                                duration: 8   },
    { id: 77, section: 'Probability', title: 'Lecture 7d. MIT Question and GATE 2021 Question',                                     duration: 13  },
    { id: 78, section: 'Probability', title: 'Lecture 7e. Expectation of Random Variable which is a Function of Random Variable',   duration: 18  },
    { id: 79, section: 'Probability', title: 'LIVE Session 6',                                                                      duration: 76  },
    { id: 80, section: 'Probability', title: 'Lecture 8a. Question number 8',                                                       duration: 21  },
    { id: 81, section: 'Probability', title: 'Lecture 8b. Question number 9, 10, 11',                                               duration: 17  },
    { id: 82, section: 'Probability', title: 'Lecture 8c. Question number 12, 13',                                                  duration: 30  },
    { id: 83, section: 'Probability', title: 'Lecture 9a. Cumulative Distribution Function',                                        duration: 31  },
    { id: 84, section: 'Probability', title: '[LIVE] Lecture 9b - Variance Intuition and Formula',                                  duration: 52  },
    { id: 85, section: 'Probability', title: '[LIVE] Lecture 9c- Variance Main Formula and Questions',                              duration: 38  },
    { id: 86, section: 'Probability', title: '[LIVE] Lecture 9d- Variance Questions',                                               duration: 45  },
    { id: 87, section: 'Probability', title: '[LIVE] Lecture 10a: Discrete random variable (Bernoulli and Binomial RVs)',            duration: 77  },
    { id: 88, section: 'Probability', title: '[LIVE] Lecture 10b. MIT Question on Binomial RV',                                     duration: 16  },
    { id: 89, section: 'Probability', title: '[LIVE] Lecture 10c. Optional and Skip - Question on Plot of PMF',                     duration: 19  },
    { id: 90, section: 'Probability', title: '[LIVE] Lecture 10d. Poisson RV',                                                      duration: 28  },
    { id: 91, section: 'Probability', title: '10d. Discrete Uniform RV Introduction',                                               duration: 15  },
    { id: 92, section: 'Probability', title: 'Lecture 11a. Introduction to Continuous Distributions | Intuition about PDF',         duration: 32  },
    { id: 93, section: 'Probability', title: 'Lecture 11b. Continuous Uniform Distribution',                                        duration: 25  },
    { id: 94, section: 'Probability', title: 'Lecture 11c. Normal Distribution',                                                    duration: 43  },
    { id: 95, section: 'Probability', title: 'Lecture 11d. Normal Distribution - 2',                                                duration: 17  },
    { id: 96, section: 'Probability', title: 'Lecture 11E. Exponential Distribution',                                               duration: 18  },
    { id: 97, section: 'Probability', title: 'Lecture 12. Statistics - Mean Mode Median',                                           duration: 35  },
    { id: 98, section: 'Probability', title: 'Weekly Quizzes - Probability',                                                        duration: 0   },
    { id: 99, section: 'Probability', title: 'Review Annotated PDFs & Homework',                                                    duration: 0   },

    // ─── Calculus (GATE 2025) ─────────────────────────────────────────────────

    { id: 100, section: 'Calculus (GATE 2025)', title: 'Lecture 1: Finding Limit of a function',                                    duration: 116 },
    { id: 101, section: 'Calculus (GATE 2025)', title: 'Lecture 2: Methods to Evaluate the Limit of a function (Live)',             duration: 111 },
    { id: 102, section: 'Calculus (GATE 2025)', title: "Lecture 3: Limits L'Hôpital's rule and Other Indeterminate forms of powers (Live)", duration: 75 },
    { id: 103, section: 'Calculus (GATE 2025)', title: 'Lecture 4: Continuity and Introduction to Differentiability',               duration: 91  },
    { id: 104, section: 'Calculus (GATE 2025)', title: 'Lecture 5A: [Optional] Recap Differentiability',                             duration: 22  },
    { id: 105, section: 'Calculus (GATE 2025)', title: 'Lecture 5A: Introduction to Minima and Maxima | The First Derivative Test', duration: 78  },
    { id: 106, section: 'Calculus (GATE 2025)', title: 'Lecture 5B: The Second Derivative Test',                                     duration: 45  },
    { id: 107, section: 'Calculus (GATE 2025)', title: 'Lecture 5B: Intermediate Mean Value Theorem | Rolle\'s theorem | Lagrange Mean Value Theorem', duration: 45 },
    { id: 108, section: 'Calculus (GATE 2025)', title: 'Lecture 5C: Few Questions on MVT Theorems (Part - 1)',                      duration: 18  },
    { id: 109, section: 'Calculus (GATE 2025)', title: 'Lecture 5C: Few Questions on MVT Theorems Part-2',                          duration: 12  },
    { id: 110, section: 'Calculus (GATE 2025)', title: 'Lecture 6: Integration',                                                    duration: 107 },
    { id: 111, section: 'Calculus (GATE 2025)', title: 'Homework Limit Calculus GATE CSE PYQs',                                     duration: 0   },
    { id: 112, section: 'Calculus (GATE 2025)', title: 'Weekly Quizzes - Calculus',                                                 duration: 0   },
    { id: 113, section: 'Calculus (GATE 2025)', title: 'Review Annotated PDFs & Homework',                                          duration: 0   },

    // ─── Calculus (Old Videos) ────────────────────────────────────────────────

    { id: 114, section: 'Calculus (Old Videos)', title: 'Limits in Calculus',                                                       duration: 50  },
    { id: 115, section: 'Calculus (Old Videos)', title: 'Continuity in Calculus',                                                   duration: 12  },
    { id: 116, section: 'Calculus (Old Videos)', title: 'Differentiability in Calculus',                                            duration: 17  },
    { id: 117, section: 'Calculus (Old Videos)', title: 'Maxima Minima in Calculus',                                                duration: 28  },
    { id: 118, section: 'Calculus (Old Videos)', title: 'Intermediate Value Theorem',                                               duration: 18  },
    { id: 119, section: 'Calculus (Old Videos)', title: "Rolle's Theorem and Examples",                                             duration: 13  },
    { id: 120, section: 'Calculus (Old Videos)', title: 'Integration with ALL GATE PYQs | Tic Tac Toe method',                      duration: 44  },
    { id: 121, section: 'Calculus (Old Videos)', title: 'LIVE Session 1: Limit and Continuity',                                     duration: 114 },
    { id: 122, section: 'Calculus (Old Videos)', title: 'LIVE Session 2: Differentiability',                                        duration: 110 },
    { id: 123, section: 'Calculus (Old Videos)', title: 'LIVE Session 3: Double Derivative and Mean Value Theorems',                duration: 96  },
    { id: 124, section: 'Calculus (Old Videos)', title: 'LIVE Session 4: Integration',                                              duration: 90  },
    { id: 125, section: 'Calculus (Old Videos)', title: 'Calculus Quiz - Weekly Quiz 14',                                           duration: 0   },
    { id: 126, section: 'Calculus (Old Videos)', title: 'Review Annotated PDFs & Homework',                                         duration: 0   },
  ],
};
