export const COURSE_DATA = [
  { "id": 1, "section": "Why Study Algorithms", "title": "1a. Why Study Algorithms", "duration": 13 },
  { "id": 2, "section": "Why Study Algorithms", "title": "1b. An algorithm that changed history And Child's algorithm", "duration": 9 },
  { "id": 3, "section": "Asymptotic Analysis and Loop Complexities", "title": "DS Videos: 5a. Introduction to Asymptotic Analysis", "duration": 17 },
  { "id": 4, "section": "Asymptotic Analysis and Loop Complexities", "title": "DS Videos: 5b. Big oh and Big omega Asymptotic Notations", "duration": 39 },
  { "id": 5, "section": "Asymptotic Analysis and Loop Complexities", "title": "DS Videos: 5c. Theta Asymptotic notation", "duration": 13 },
  { "id": 6, "section": "Asymptotic Analysis and Loop Complexities", "title": "DS Videos: 5d. What is Asymptotic comparison | how LOG works | rice grain story", "duration": 31 },
  { "id": 7, "section": "Asymptotic Analysis and Loop Complexities", "title": "DS Videos: 5e. Comparing Different Functions Asymptotically", "duration": 53 },
  { "id": 8, "section": "Asymptotic Analysis and Loop Complexities", "title": "DS Videos: 5f. Little Oh Little Omega | Properties of asymptotic notation", "duration": 36 },
  { "id": 9, "section": "Asymptotic Analysis and Loop Complexities", "title": "DS Videos: 6a.Formal set notation of Asymptote symbols", "duration": 7 },
  { "id": 10, "section": "Asymptotic Analysis and Loop Complexities", "title": "DS Videos: 6b. Asymptotic Notations GATE PYQs", "duration": 21 },
  { "id": 11, "section": "Asymptotic Analysis and Loop Complexities", "title": "DS Videos: 6c. Analysing the loops time complexity", "duration": 29 },
  { "id": 12, "section": "Asymptotic Analysis and Loop Complexities", "title": "6d. Time Complexity of loops -2", "duration": 17 },
  { "id": 13, "section": "Asymptotic Analysis and Loop Complexities", "title": "DS Videos: 7a. Brief about Best Case, Worst Case", "duration": 22 },
  { "id": 14, "section": "Asymptotic Analysis and Loop Complexities", "title": "DS Videos: 7b. More about Best Case, Worst Case", "duration": 26 },
  { "id": 15, "section": "Asymptotic Analysis and Loop Complexities", "title": "DS Videos: 7c. Questions on Algorithmic notations", "duration": 5 },
  { "id": 16, "section": "Time Complexity of Recursive Programs", "title": "2a. Introduction to recurrence relations", "duration": 15 },
  { "id": 17, "section": "Time Complexity of Recursive Programs", "title": "2b. Solving recurrence using Iteration Method", "duration": 9 },
  { "id": 18, "section": "Time Complexity of Recursive Programs", "title": "2c. More Examples of Iteration Method", "duration": 10 },
  { "id": 19, "section": "Time Complexity of Recursive Programs", "title": "3a. Solving recurrence using Tree Method", "duration": 24 },
  { "id": 20, "section": "Time Complexity of Recursive Programs", "title": "3b. More Examples Tree Method", "duration": 16 },
  { "id": 21, "section": "Time Complexity of Recursive Programs", "title": "3c. Even More Examples Tree Method", "duration": 5 },
  { "id": 22, "section": "Time Complexity of Recursive Programs", "title": "3d. More Examples Tree Method", "duration": 12 },
  { "id": 23, "section": "Time Complexity of Recursive Programs", "title": "4a. Masters Theorem Idea and examples", "duration": 27 },
  { "id": 24, "section": "Time Complexity of Recursive Programs", "title": "4b. Examples On Master Theorem", "duration": 4 },
  { "id": 25, "section": "Time Complexity of Recursive Programs", "title": "4c. Proof of Master Theorem", "duration": 16 },
  { "id": 26, "section": "Time Complexity of Recursive Programs", "title": "5a. Generalised Master Theorem", "duration": 6 },
  { "id": 27, "section": "Time Complexity of Recursive Programs", "title": "5b. Extended Master Theorem", "duration": 15 },
  { "id": 28, "section": "Time Complexity of Recursive Programs", "title": "5c. Various Examples of Master Theorem", "duration": 7 },
  { "id": 29, "section": "Time Complexity of Recursive Programs", "title": "5d. Problems that master theorem can not solve", "duration": 5 },
  { "id": 30, "section": "Time Complexity of Recursive Programs", "title": "6a. Introduction to change to variable method", "duration": 15 },
  { "id": 31, "section": "Time Complexity of Recursive Programs", "title": "6b. Examples on Change of Variable", "duration": 12 },
  { "id": 32, "section": "Time Complexity of Recursive Programs", "title": "6c. Few more examples on change of variable method", "duration": 5 },
  { "id": 33, "section": "Time Complexity of Recursive Programs", "title": "6d. Some More variation", "duration": 17 },
  { "id": 34, "section": "Divide and Conquer Algorithms", "title": "7a. Introduction to Divide and Conquer Algorithm", "duration": 24 },
  { "id": 35, "section": "Divide and Conquer Algorithms", "title": "7b. Maximum of an array using D and C", "duration": 10 },
  { "id": 36, "section": "Divide and Conquer Algorithms", "title": "7c. Example 2- Sum of an array", "duration": 5 },
  { "id": 37, "section": "Divide and Conquer Algorithms", "title": "7d. Example 3- Search in an array", "duration": 6 },
  { "id": 38, "section": "Divide and Conquer Algorithms", "title": "7e. Example 4 - Dumb Sort", "duration": 8 },
  { "id": 39, "section": "Divide and Conquer Algorithms", "title": "8a. Introduction to Merge Sort algorithm", "duration": 11 },
  { "id": 40, "section": "Divide and Conquer Algorithms", "title": "8b. Heart of Merge Sort- Merge Procedure", "duration": 16 },
  { "id": 41, "section": "Divide and Conquer Algorithms", "title": "8c. Merge Procedure -2", "duration": 23 },
  { "id": 42, "section": "Divide and Conquer Algorithms", "title": "8d. Merge Sort Recursive tree with example", "duration": 13 },
  { "id": 43, "section": "Divide and Conquer Algorithms", "title": "8e. Merge Sort Analysis", "duration": 21 },
  { "id": 44, "section": "Divide and Conquer Algorithms", "title": "9a. Merge Sort questions -1", "duration": 11 },
  { "id": 45, "section": "Divide and Conquer Algorithms", "title": "9b. Merge Sort questions -2", "duration": 14 },
  { "id": 46, "section": "Divide and Conquer Algorithms", "title": "9c. More Questions on Merge sort", "duration": 26 },
  { "id": 47, "section": "Divide and Conquer Algorithms", "title": "10a. Iterative (or Bottom-up) Merge sort", "duration": 11 },
  { "id": 48, "section": "Divide and Conquer Algorithms", "title": "10b. GATE 1999 question on Bottom up Merge Sort", "duration": 2 },
  { "id": 49, "section": "Divide and Conquer Algorithms", "title": "10c. Time Complexity of Iterative Merge sort", "duration": 17 },
  { "id": 50, "section": "Divide and Conquer Algorithms", "title": "10d. Implementation of Iterative Merge sort", "duration": 13 },
  { "id": 51, "section": "Divide and Conquer Algorithms", "title": "11a. Merging k sorted arrays Part 1", "duration": 22 },
  { "id": 52, "section": "Divide and Conquer Algorithms", "title": "11b. Merging k sorted arrays Part 2", "duration": 22 },
  { "id": 53, "section": "Divide and Conquer Algorithms", "title": "11d. Definition of Stable and In-place sorting", "duration": 17 },
  { "id": 54, "section": "Divide and Conquer Algorithms", "title": "[DELETED] In Place and Space Complexity", "duration": 5 },
  { "id": 55, "section": "Maximum and Minimum Of Numbers", "title": "12a. Maximum and Second Max of an array", "duration": 19 },
  { "id": 56, "section": "Maximum and Minimum Of Numbers", "title": "12b. Second maximum using Tournament Method", "duration": 31 },
  { "id": 57, "section": "Maximum and Minimum Of Numbers", "title": "12c. How to keep track for candidates of Second maximum", "duration": 10 },
  { "id": 58, "section": "Maximum and Minimum Of Numbers", "title": "12d. Maximum and Minimum of an array", "duration": 35 },
  { "id": 59, "section": "Maximum and Minimum Of Numbers", "title": "13a. Tournament Method and D&C for Max Min", "duration": 25 },
  { "id": 60, "section": "Maximum and Minimum Of Numbers", "title": "13b. Cormen questions", "duration": 7 },
  { "id": 61, "section": "Maximum and Minimum Of Numbers", "title": "13c. GATE Questions", "duration": 11 },
  { "id": 62, "section": "Maximum and Minimum Of Numbers", "title": "14a. Algorithm Analysis", "duration": 31 },
  { "id": 63, "section": "Maximum and Minimum Of Numbers", "title": "14b. Questions on Algorithmic notations", "duration": 5 },
  { "id": 64, "section": "Divide and Conquer Algorithms (Part-2)", "title": "15a. Counting inversion with Netflix and Amazon Example", "duration": 17 },
  { "id": 65, "section": "Divide and Conquer Algorithms (Part-2)", "title": "15b. Numerical questions on Counting Inversion", "duration": 15 },
  { "id": 66, "section": "Divide and Conquer Algorithms (Part-2)", "title": "15c. Counting Inversions using BruteForce method", "duration": 12 },
  { "id": 67, "section": "Divide and Conquer Algorithms (Part-2)", "title": "16a. Heart of counting Inversion", "duration": 24 },
  { "id": 68, "section": "Divide and Conquer Algorithms (Part-2)", "title": "16b. Working Example of Counting Inversion", "duration": 13 },
  { "id": 69, "section": "Divide and Conquer Algorithms (Part-2)", "title": "16c. Counting Inversion question", "duration": 10 },
  { "id": 70, "section": "Divide and Conquer Algorithms (Part-2)", "title": "17a. Closest pair in 2 D", "duration": 33 },
  { "id": 71, "section": "Divide and Conquer Algorithms (Part-2)", "title": "17b. Closest pair-2", "duration": 18 },
  { "id": 72, "section": "Divide and Conquer Algorithms (Part-2)", "title": "17c. Exponent of a number", "duration": 7 },
  { "id": 73, "section": "Divide and Conquer Algorithms (Part-2)", "title": "17d. Matrix Multiplication", "duration": 21 },
  { "id": 74, "section": "Divide and Conquer Algorithms (Part-2)", "title": "18a. Introduction to Quick Sort", "duration": 28 },
  { "id": 75, "section": "Divide and Conquer Algorithms (Part-2)", "title": "18b. Working Example of Quick Sort", "duration": 30 },
  { "id": 76, "section": "Divide and Conquer Algorithms (Part-2)", "title": "18c. Quick sort Analysis and Randomised quick sort", "duration": 40 },
  { "id": 77, "section": "Divide and Conquer Algorithms (Part-2)", "title": "18d. GATE 2014 question", "duration": 11 },
  { "id": 78, "section": "Divide and Conquer Algorithms (Part-2)", "title": "18e. Questions on quick sort", "duration": 23 },
  { "id": 79, "section": "Divide and Conquer Algorithms (Part-2)", "title": "18f. Average case analysis of quick sort", "duration": 5 },
  { "id": 80, "section": "Divide and Conquer Algorithms (Part-2)", "title": "19a. The Select algorithm", "duration": 25 },
  { "id": 81, "section": "Divide and Conquer Algorithms (Part-2)", "title": "19b. Binary Search", "duration": 28 },
  { "id": 82, "section": "Sorting Algorithms", "title": "20a .Bubble Sort", "duration": 27 },
  { "id": 83, "section": "Sorting Algorithms", "title": "20b .Insertion Sort", "duration": 24 },
  { "id": 84, "section": "Sorting Algorithms", "title": "20c .Bubble Sort and Insertion Sort", "duration": 34 },
  { "id": 85, "section": "Sorting Algorithms", "title": "20d. Selection Sort and Heap Sort", "duration": 37 },
  { "id": 86, "section": "Sorting Algorithms", "title": "20e. Decision Tree", "duration": 52 },
  { "id": 87, "section": "Sorting Algorithms", "title": "20f. Counting Sort and Radix Sort", "duration": 34 },
  { "id": 88, "section": "BFS and DFS", "title": "21a. Introduction to Graphs", "duration": 19 },
  { "id": 89, "section": "BFS and DFS", "title": "21b. intuition for graph search methods", "duration": 24 },
  { "id": 90, "section": "BFS and DFS", "title": "21c. Introduction to DFS", "duration": 23 },
  { "id": 91, "section": "BFS and DFS", "title": "21d. DFS Implementation and Time complexity", "duration": 40 },
  { "id": 92, "section": "BFS and DFS", "title": "22b. DFS Edge Classifications", "duration": 27 },
  { "id": 93, "section": "BFS and DFS", "title": "22c. Questions on DFS Edge Classification", "duration": 30 },
  { "id": 94, "section": "BFS and DFS", "title": "22d. Back-edge and cycle question", "duration": 18 },
  { "id": 95, "section": "BFS and DFS", "title": "23a. DFS Application 1- Cycles in graph", "duration": 31 },
  { "id": 96, "section": "BFS and DFS", "title": "23b. GATE 2007 question on DAG finish time", "duration": 21 },
  { "id": 97, "section": "BFS and DFS", "title": "23c. DFS Application 2 Topological sort", "duration": 19 },
  { "id": 98, "section": "BFS and DFS", "title": "23d. DFS Application 3 Articulation Point", "duration": 46 },
  { "id": 99, "section": "BFS and DFS", "title": "24a. Introduction to BFS", "duration": 28 },
  { "id": 100, "section": "BFS and DFS", "title": "24b. BFS Observations and Edge Classification", "duration": 37 },
  { "id": 101, "section": "BFS and DFS", "title": "25. BFS Applications", "duration": 29 },
  { "id": 102, "section": "Shortest Paths Algorithms", "title": "26a. Introduction to Greedy Algorithms & Dijkstra", "duration": 56 },
  { "id": 103, "section": "Shortest Paths Algorithms", "title": "26b. Dijkstra code and Working Example 1", "duration": 17 },
  { "id": 104, "section": "Shortest Paths Algorithms", "title": "26c. Dijkstra Working Example 2", "duration": 15 },
  { "id": 105, "section": "Shortest Paths Algorithms", "title": "26d. Dijkstra Working Example 3", "duration": 10 },
  { "id": 106, "section": "Shortest Paths Algorithms", "title": "27a. Dijkstra on negative weights", "duration": 44 },
  { "id": 107, "section": "Shortest Paths Algorithms", "title": "27b. Video From DS Course: Priority Queues", "duration": 17 },
  { "id": 108, "section": "Shortest Paths Algorithms", "title": "27c. Dijkstra Time Complexity", "duration": 33 },
  { "id": 109, "section": "Shortest Paths Algorithms", "title": "27d. Dijkstra Time Complexity on variant data structures", "duration": 10 },
  { "id": 110, "section": "Shortest Paths Algorithms", "title": "28a. DAG Shortest Path", "duration": 17 },
  { "id": 111, "section": "Shortest Paths Algorithms", "title": "28b. Intuition Behind Bellman Ford Algorithm", "duration": 28 },
  { "id": 112, "section": "Shortest Paths Algorithms", "title": "28c. Examples of Bellman Ford | Time complexity", "duration": 36 },
  { "id": 113, "section": "Shortest Paths Algorithms", "title": "28d. Bellman ford proof and Early termination", "duration": 23 },
  { "id": 114, "section": "Minimum Spanning Tree Algorithms", "title": "29a. Why Minimum Spanning Trees", "duration": 22 },
  { "id": 115, "section": "Minimum Spanning Tree Algorithms", "title": "29b. Cut and Cycle properties of MST", "duration": 22 },
  { "id": 116, "section": "Minimum Spanning Tree Algorithms", "title": "29c. Kruskal Algorithm", "duration": 24 },
  { "id": 117, "section": "Minimum Spanning Tree Algorithms", "title": "30a. Questions on MSTs", "duration": 23 },
  { "id": 118, "section": "Minimum Spanning Tree Algorithms", "title": "30b. Prims Algorithm", "duration": 27 },
  { "id": 119, "section": "Minimum Spanning Tree Algorithms", "title": "30c. Prims and Dijkstra Similarity", "duration": 39 },
  { "id": 120, "section": "Minimum Spanning Tree Algorithms", "title": "30d. Single Example for Prims and Dijkstra both", "duration": 8 },
  { "id": 121, "section": "Minimum Spanning Tree Algorithms", "title": "31a. Interesting Questions on MSTs", "duration": 31 },
  { "id": 122, "section": "Minimum Spanning Tree Algorithms", "title": "31b. Two Most Popular Template Questions in MSTs", "duration": 38 },
  { "id": 123, "section": "Minimum Spanning Tree Algorithms", "title": "31c. Four Cases in MSTs", "duration": 58 },
  { "id": 124, "section": "More Greedy Algorithms", "title": "32a. Huffman Encoding Concept and Questions", "duration": 32 },
  { "id": 125, "section": "More Greedy Algorithms", "title": "32b. Question on Huffman Encoding", "duration": 3 },
  { "id": 126, "section": "More Greedy Algorithms", "title": "32c. Huffman Encoding Time Complexity", "duration": 7 },
  { "id": 127, "section": "More Greedy Algorithms", "title": "32d. Nice Questions on Huffman Encoding", "duration": 8 },
  { "id": 128, "section": "More Greedy Algorithms", "title": "33a. Berkeley and MIT Questions on Huffman Encoding", "duration": 7 },
  { "id": 129, "section": "More Greedy Algorithms", "title": "33b. Huffman Encoding Question Based on Tree Variance", "duration": 25 },
  { "id": 130, "section": "More Greedy Algorithms", "title": "33c. Optimal Merge Pattern", "duration": 5 },
  { "id": 131, "section": "More Greedy Algorithms", "title": "34a. Interval Scheduling Problem Algorithm Ideas", "duration": 36 },
  { "id": 132, "section": "More Greedy Algorithms", "title": "34b. Interval Scheduling Problem Algorithm", "duration": 8 },
  { "id": 133, "section": "More Greedy Algorithms", "title": "34c. Proving Optimality using Exchange Techniques", "duration": 24 },
  { "id": 134, "section": "More Greedy Algorithms", "title": "34d. Other Variants of Interview Scheduling", "duration": 11 },
  { "id": 135, "section": "More Greedy Algorithms", "title": "34e. Job Scheduling With Deadlines", "duration": 15 },
  { "id": 136, "section": "More Greedy Algorithms", "title": "35a. Fractional Knapsack", "duration": 27 },
  { "id": 137, "section": "More Greedy Algorithms", "title": "35b. Fractional Knapsack in O(n)", "duration": 12 },
  { "id": 138, "section": "Dynamic Programming", "title": "36a. Introduction to DP", "duration": 31 },
  { "id": 139, "section": "Dynamic Programming", "title": "36b. Example 1- Climbing Stairs", "duration": 9 },
  { "id": 140, "section": "Dynamic Programming", "title": "36c. Example 2 MCQ on DP", "duration": 10 },
  { "id": 141, "section": "Dynamic Programming", "title": "36d. Example 3- Climbing Stairs Cost", "duration": 11 },
  { "id": 142, "section": "Dynamic Programming", "title": "37a. Total Probability and DP", "duration": 22 },
  { "id": 143, "section": "Dynamic Programming", "title": "37b. Order of Table Filling", "duration": 23 },
  { "id": 144, "section": "Dynamic Programming", "title": "37c. DP vs Divide and Conquer", "duration": 23 },
  { "id": 145, "section": "Dynamic Programming", "title": "38a. Longest Common Subsequence | BruteForce", "duration": 26 },
  { "id": 146, "section": "Dynamic Programming", "title": "38b. Longest Common Subsequence using DP", "duration": 35 },
  { "id": 147, "section": "Dynamic Programming", "title": "38c. Total Calls vs Unique Calls in LCS", "duration": 8 },
  { "id": 148, "section": "Dynamic Programming", "title": "38d. GATE 2009 Easy Question", "duration": 1 },
  { "id": 149, "section": "Dynamic Programming", "title": "39a. Running Example on LCS", "duration": 27 },
  { "id": 150, "section": "Dynamic Programming", "title": "39b. GATE 2014 Question on LCS", "duration": 4 },
  { "id": 151, "section": "Dynamic Programming", "title": "39c. LCS Applications", "duration": 1 },
  { "id": 152, "section": "Dynamic Programming", "title": "39d. Another way of writting LCS Recursion", "duration": 13 },
  { "id": 153, "section": "Dynamic Programming", "title": "40a. Introduction to Matrix Chain Multiplication", "duration": 38 },
  { "id": 154, "section": "Dynamic Programming", "title": "40b. Number of Ways to Multiply n Matrices", "duration": 10 },
  { "id": 155, "section": "Dynamic Programming", "title": "40c. Recursive Formulation of MCM", "duration": 51 },
  { "id": 156, "section": "Dynamic Programming", "title": "40d. Example on Matrix Chain Multiplication", "duration": 9 },
  { "id": 157, "section": "Dynamic Programming", "title": "40e. Time Complexity of Matrix chain Multiplication", "duration": 14 },
  { "id": 158, "section": "Dynamic Programming", "title": "41a. Greedy Strategy on 0-1 Knapsack Problem", "duration": 15 },
  { "id": 159, "section": "Dynamic Programming", "title": "41b. Recursive Formulation of 0-1 Knapsack", "duration": 23 },
  { "id": 160, "section": "Dynamic Programming", "title": "41c. One More Running Example on 0-1 Knapsack", "duration": 8 },
  { "id": 161, "section": "Dynamic Programming", "title": "41d. Calls in Knapsack and Time Complexity", "duration": 10 },
  { "id": 162, "section": "Dynamic Programming", "title": "41e. Solving 0-1 Knapsack with Bottom Up Approach", "duration": 18 },
  { "id": 163, "section": "More Dynamic Programming Algorithms", "title": "42a. Subset Sum Problem", "duration": 29 },
  { "id": 164, "section": "More Dynamic Programming Algorithms", "title": "42b. Coin Change Problem", "duration": 13 },
  { "id": 165, "section": "More Dynamic Programming Algorithms", "title": "42c. DP Vs Greedy vs Divide and Conquer", "duration": 23 },
  { "id": 166, "section": "More Dynamic Programming Algorithms", "title": "42d. Floyd Warshall Algorithm", "duration": 15 },
  { "id": 167, "section": "More Dynamic Programming Algorithms", "title": "42e. Travelling Salesman", "duration": 6 }
];
